name: medicine_remainderrr
description: A medicine reminder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_local_notifications:
    git:
      url: https://github.com/Jayypatell23/flutter_local_notifications
      ref: main
  timezone: ^0.9.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/alarm.mp3 